version: "3.9"

services:
  scraper-app:
    build: .                # Dockerfile is in the same folder
    container_name: scraper_app
    restart: always
    ports:
      - "2000:2000"         # map container port to host
    networks:
      - lordflix_net

networks:
  lordflix_net:
    external: true
